/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x3D, 0x23, 0x68, 0xC4, 0x1F, 0x4E, 0x55, 0x8C}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 3, 5 }

#define MOUSE_EXTENDED_REPORT

#define PLOOPY_DRAGSCROLL_INVERT
// #define PLOOPY_DRAGSCROLL_MOMENTARY
#define PLOOPY_DRAGSCROLL_DIVISOR_H 60.0
#define PLOOPY_DRAGSCROLL_DIVISOR_V 60.0

#define PLOOPY_DPI_OPTIONS { 400, 600, 800, 1000 }
#define PLOOPY_DPI_DEFAULT 1

#define REARMAN_PLOOPY_RELEASE_ADHOC_DISTANCE 5
