#pragma once

#define VIAL_KEYBOARD_UID {0x03, 0xB6, 0xD4, 0x8E, 0xDC, 0x54, 0xAE, 0x96}
#define VIAL_UNLOCK_COMBO_ROWS {0,0}
#define VIAL_UNLOCK_COMBO_COLS {0,1}

#define NO_ACTION_FUNCTION
#define NO_ACTION_ONESHOT
#undef TAPPING_TERM
#define TAPPING_TERM 150
#define TAPPING_TOGGLE 1
#define IGNORE_MOD_TAP_INTERRUPT
#define RGBLIGHT_LAYERS
#undef RGBLIGHT_ANIMATIONS
