#pragma once

#define VIAL_KEYBOARD_UID {0x03, 0xB6, 0xD4, 0x8E, 0xDC, 0x54, 0xAE, 0x96}
#define VIAL_UNLOCK_COMBO_ROWS {0,0}
#define VIAL_UNLOCK_COMBO_COLS {0,1}

#define NO_ACTION_FUNCTION
#define NO_ACTION_MACRO
#define DISABLE_LEADER

#undef TAPPING_TERM
#define TAPPING_TERM 150
#define TAPPING_TOGGLE 1

#define RGBLIGHT_LAYERS
#undef RGBLIGHT_EFFECT_ALTERNATING
#undef RGBLIGHT_EFFECT_BREATHING
#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_RAINBOW_MOOD
#undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
#undef RGBLIGHT_EFFECT_RGB_TEST
#undef RGBLIGHT_EFFECT_SNAKE
#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
#undef RGBLIGHT_EFFECT_TWINKLE
#undef RGBLIGHT_EFFECT_BREATHE_CENTER
