VIA_ENABLE = yes
VIAL_ENABLE = yes
LIO_ENABLE = no

AUTO_SHIFT_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
EXTRAFLAGS += -flto
KEY_LOCK_ENABLE = no
KEY_OVERRIDE_ENABLE = no
LEADER_ENABLE = no
MOUSEKEY_ENABLE = no
SWAP_HANDS_ENABLE = no
